### ISSUE TITLE
Some styling issues on larger 4K display

### ISSUE THREAD

**Issue by tamburra** [prayag17/JellyFlix#11]
I spun up Jellyfin on a windows 10 box displaying on a large format 4K TV the other day and snapped some pics and highlighted some key parts I noticed while exploring. 

Display Resolution = 3840 x 2160
Size of text, apps, and other items setting is at 225%.

![image](https://user-images.githubusercontent.com/16267805/116784014-dd849200-aa5f-11eb-9d4d-8c8835d07b2d.jpeg)

"Please Log
In"

Would be easier on the eyes if this was one line instead of two. 

![image](https://user-images.githubusercontent.com/16267805/116784019-e37a7300-aa5f-11eb-9644-50c9f0c9ecf6.jpeg)

Top portion of tv show main view page looks great!

![image](https://user-images.githubusercontent.com/16267805/116784062-14f33e80-aa60-11eb-832a-84e6d09bb24b.jpeg)

Scroll a little further down and you can see that some text is being cut off from the header section.

![image](https://user-images.githubusercontent.com/16267805/116784079-29cfd200-aa60-11eb-898d-b698b4897816.jpeg)

Text title and logo are both shown on the season page.

![image](https://user-images.githubusercontent.com/16267805/116784100-508e0880-aa60-11eb-948e-e2bafee78e37.jpeg)

**Comment by prayag17** [comment]
This issue has been fixed by me
