### ISSUE TITLE
Wrong/Not Working Fonts

### ISSUE THREAD

**Issue by SmokeyOdin** [prayag17/JellyFlix#12]
![2021-05-02 (2)](https://user-images.githubusercontent.com/82475406/116823348-e8cce000-ab7b-11eb-94ef-095395ee2177.png)

Only using the JellyFlix css gives a font that doesn't match what the images show.

**Comment by prayag17** [comment]
The font location is not the issue, this issue might be because you might be blocking assets.nflxext.com
