### ISSUE TITLE
Improve Jellyflix for mobile 

### ISSUE THREAD

**Issue by userobvixus** [prayag17/JellyFlix#13]
Hi, I hope you doing great !
I think I find a mistake with jellyflix when I use Jellyfin with my iOS app I don’t have title of episode under it and just the end for the description it look weird I send a video for showing you because it’s hard to me to explain.
Thanks for your work and your help have a nice day !!

**Comment by userobvixus** [comment]
![852645C6-A44D-4231-95E0-1E7C21E8923F](https://user-images.githubusercontent.com/73913514/118727472-162fb400-b833-11eb-941b-213b5a3c9d71.png)

I can’t link the video so I send a screenshot !

**Comment by userobvixus** [comment]
![5A179859-913A-4F57-A220-42A436038D94](https://user-images.githubusercontent.com/73913514/118728935-47a97f00-b835-11eb-85c2-f25ea49a2f01.jpeg)

Same problem with safari sorry for spamming :) 
Have a good day !

**Comment by userobvixus** [comment]
I think the title is hiding behind the picture of the episode because the with the default skin it look like this ![image](https://user-images.githubusercontent.com/73913514/118730997-c7851880-b838-11eb-8ce2-97aac817f937.png)

**Comment by prayag17** [comment]
I dont see the episode issue on any of my devices...though I am working on making the title page on mobile better

**Comment by prayag17** [comment]
I have fixed the episode issue...can you confirm?

**Comment by userobvixus** [comment]
Thanks you it look very nice now, good works !
Have a nice day ! ![image](https://user-images.githubusercontent.com/73913514/119477556-58835480-bd4f-11eb-9e03-b485a53ace9f.png)
