### ISSUE TITLE
new version removes title names below posters

### ISSUE THREAD

**Issue by b-zig** [prayag17/JellyFlix#18]
Hi, the new logo version (non custom) removes the titles under the poster. 

I'm using FireFox, was this the intention? I switched to the custom logo version and its back. 

Image below: 
![image](https://user-images.githubusercontent.com/88641911/144071341-78b54fd6-7b92-4bf0-8afb-ac9ae4165230.png)

Thanks for all your work on this custom CSS.

**Comment by prayag17** [comment]
It is not a bug, I made it that way cause that is what Netflix does but if you want to force see the title ask me

**Comment by b-zig** [comment]
thanks. I didn't know that was the expected behaviour. Would we be able to get a version with the static titles?

**Comment by prayag17** [comment]
Sure, use this:

```css
.cardText {
    opacity: 1 !important;
}
```
