### ISSUE TITLE
Feature Request: Option for smaller "cards" or "posters" in music library's 

### ISSUE THREAD

**Issue by evilalmus** [prayag17/JellyFlix#2]
This skin looks absolutely great for everything except the Music catalog. In music the tiles are huge and it makes the catalog almost impossible to browse in anything other than "list" mode.

It would be really nice to either have smaller cards for the music library or more options to choose different sizes.

**Comment by chp-1960** [comment]
I agree with evilalmus. The music and TV catalogs show huge tiles. even uglier when the card is empty

**Comment by prayag17** [comment]
Can you send me the images?

**Comment by evilalmus** [comment]
Sure, here are three screenshots. All taken on a 1080p monitor:
First one is at 100% zoom in the music library:
![jellyflix_100_music](https://user-images.githubusercontent.com/18252672/99896419-32b4b000-2c45-11eb-8e00-df3db8d9484b.png)

Next one is at 90% zoom, same music library
![jellyflix_90_music](https://user-images.githubusercontent.com/18252672/99896434-45c78000-2c45-11eb-9a12-661ec62dfae1.png)

Lastly, the movie library, this is what I think the music library *should* look like:
![jellyflix_100_movies](https://user-images.githubusercontent.com/18252672/99896441-668fd580-2c45-11eb-801e-22555ed13de3.png)

**Comment by prayag17** [comment]
I am working on a fix, but your zoom is not right for the movie posters. Try Zooming-in or out till those poster lines disappear.

**Comment by chp-1960** [comment]
I Have same behavior. look at my screenshot
While listing all the medias:
![Bad_JellyFix2](https://user-images.githubusercontent.com/69758416/99905725-fe87d080-2cd2-11eb-9a1e-572f82593f98.jpg)

And on that one the description of the media is mid-hidden:
![Bad_JellyFix1](https://user-images.githubusercontent.com/69758416/99905694-ba94cb80-2cd2-11eb-8640-1060e6ae3e6e.jpg)

**Comment by chp-1960** [comment]
Oups.. Sory.. The pictures were inverted while copy. The first one is for media description and the second while browsing the medias.

**Comment by chp-1960** [comment]
While browsing the medias, If I change the view to "logo" mode, it shows this . But I have to change manually for each folder. Further more it don't change what is shown in media description.

![Bad_JellyFix3](https://user-images.githubusercontent.com/69758416/99905954-77d3f300-2cd4-11eb-9bf9-f286beeef0b4.jpg)

You can see also, on that screenshot, there is an ugly undefined black line at the bottom of the logo.

**Comment by chp-1960** [comment]
I have to add it show the same big tiles while browsing the playlists

**Comment by prayag17** [comment]
I am currently not able to work on jellyfin, so pleas wait few days for this fix

**Comment by prayag17** [comment]
The issue has been fixed by removing the compact posters
