### ISSUE TITLE
Feature Request / Fix: 

### ISSUE THREAD

**Issue by docfactory37** [prayag17/JellyFlix#20]
Great theme have just applied and love it :)

i have just noticed that if you apply the standard Jellyfin-Blue instead of the NetFlix Red that the login screen still shows the Red not the  Jellyfin-Blue 

![image](https://user-images.githubusercontent.com/20963053/144767053-bb775cd5-06b2-4a08-87de-c94d9c78eff5.png)
See in Red box.

also notice this in the Cast & Crew if images are missing it is red not the Jellyfin-Blue

![image](https://user-images.githubusercontent.com/20963053/144767112-bfbc93f9-61af-4e7d-8333-62d3c033a7fd.png)

Also noticed that there is a lot of padding where the Description is to the Next Up is this intended (i don't use Netflix)  

![image](https://user-images.githubusercontent.com/20963053/144767391-a324eb80-4b39-443f-9941-297a6616d04b.png)

not sure if this can be fixed but thought i would advise of this.

**Comment by prayag17** [comment]
The title page spacing can be made so that it would allow content to come up but it looked bad

**Comment by docfactory37** [comment]
Hi @prayag17 I just tested your change it still showing red in the cast & crew
