### ISSUE TITLE
Solution to scrolling bug in series seasons in the skin

### ISSUE THREAD

**Issue by Mr-Vladi** [prayag17/JellyFlix#21]
```
.layout-mobile .itemsContainer {
  width: calc(100vw - 6.6%);
  overflow: scroll hidden;
  padding: 0 3.3%;
}
```

Add, this part of CSS, this solves a problem that prevents scrolling in the seasons section of the series when using mobile.

**Comment by Mr-Vladi** [comment]
Ok, forget it seems to be broken hahaha, well there is a problem in the latest version that does not allow to move the seasons of the series on mobiles.
😉

**Comment by Mr-Vladi** [comment]
![image](https://user-images.githubusercontent.com/42224150/144898029-2967fa76-a776-4020-8bc9-149747000738.png)

![image](https://user-images.githubusercontent.com/42224150/144898131-b04dc99e-e86e-4cf5-95a7-860c795a74b2.png)


I'm on the latest version and for some reason, sometimes the mobile version works fine, but sometimes it just looks like this
By the way, the seasons stop moving if you don't put the code I put above

**Comment by prayag17** [comment]
> ![image](https://user-images.githubusercontent.com/42224150/144898029-2967fa76-a776-4020-8bc9-149747000738.png)

Where do you see this issue?

**Comment by Mr-Vladi** [comment]
The problem persists, it seems that it has not been solved, to this I add that a second problem is occurring with the desktop version and metadata, since now it is not shown either.
![Captura de pantalla 2021-12-08 080818](https://user-images.githubusercontent.com/42224150/145214184-7fbd0108-3e66-43b5-9fc1-7fd402f15a94.png)
**Here you can see how the metadata is not complete.**
![Captura de pantalla 2021-12-08 080846](https://user-images.githubusercontent.com/42224150/145214229-ed73813d-183d-4da3-aa37-862637157234.png)
**And here the problem remains in the mobile version**


This affects the entire content, no matter if it is a Series or Movie or a different one.

**Comment by Mr-Vladi** [comment]
```
.itemName {
    /* margin: 0.5em 0 !important; */
}
```

Esto hay que eliminarlo en logo.css, esto parece solucionar el problema con error visual de la metadata
![Captura de pantalla 2021-12-08 080818](https://user-images.githubusercontent.com/42224150/145215791-f594a3f0-a481-4600-9ac1-28794cf3024f.png)
![image](https://user-images.githubusercontent.com/42224150/145215859-61ba0d89-06b4-459c-9001-59fd2172317c.png)
Aquí ya eliminado eso en logo.css  :67

**Comment by Mr-Vladi** [comment]
Ok, forget my suggestion, I cleared the Jellyfin cache and in incognito mode and there seems to be no problem with the metadata on desktop, however the mobile version is still giving problems.

**Comment by prayag17** [comment]
The mobile version will be fixed

**Comment by Mr-Vladi** [comment]
What do you mean?

**Comment by prayag17** [comment]
It means that I will fix it soon as I am busy with other stuff

**Comment by Mr-Vladi** [comment]
Yes, sorry, my Spanish translator didn't understand the "fixed", thanks for clarifying it.  😅

**Comment by prayag17** [comment]
No problem man
