### ISSUE TITLE
[Feature request] : add more than 4 users cards on login

### ISSUE THREAD

**Issue by lightsabata** [prayag17/JellyFlix#23]
Hi,
I use your theme since last week and it is by far the most appealing.
y use jellyfin and your theme for my friends and since i have created more than 4 account, some are not displayed on the login so i have complains that is not faire for those who aren't on login page.
is it possible for you to add more?
And by the way, there is a possibility that hay all show directly on login so the users have not to scroll to the left ? (so they can se and feel they're a part of a big family ?

thank you in a advance and for your work

**Comment by prayag17** [comment]
I don't think it would be useful cause that would break for smaller displays.
