### ISSUE TITLE
Feature Request: Ability to click on title/logo to go to series main page

### ISSUE THREAD

**Issue by DarkViper609** [prayag17/JellyFlix#24]
When stuff get added to JellyFin, They like to take you directly to that episode, any way you can give better pathing, example, I click on Season 3 of a show episode 4, If I click on season 3, I am stuck there.. no way to get to the tv show main directory unless you go to shows and browse that way.

Unless I am missing something.

**Comment by prayag17** [comment]
I won't be able to add that. The logos don't have a link in the JF HTML so there is nothing I can do about that

**Comment by prayag17** [comment]
I have added this feature to the skin !!!
css:

```css
@import url("https://cdn.jsdelivr.net/gh/prayag17/JellyFlix@9.1.0/default.css");
@import url("https://cdn.jsdelivr.net/gh/prayag17/JellyFlix@9.1.0/addons/Logo.css");
```

**Comment by DarkViper609** [comment]
Sweet thanks, That is perfect

**Comment by prayag17** [comment]
Hey, use 9.1.1

**Comment by DarkViper609** [comment]
I keep it on the latest version to keep up to date on the great theme :) Didn't know if you want me to create a new suggestion or not, but anyway to get the "video play button" on everything else? the square play icon I mean.

Thanks for your hard work.
