### ISSUE TITLE
live tv

### ISSUE THREAD

**Issue by Kin1976** [prayag17/JellyFlix#27]
with this theme in live tv i cannot scroll through the guide 
the other issue is it doesnt seem to change for my firesticks  it does work on pc and tablet 
once i reboot it all goes to default 
also green  to repos and jellyfin

**Comment by Kin1976** [comment]
doesnt  work with shield either it seems like anything with tv and it is still goes to default if i restart server still kinda at a loss trying everything i can hope im not making it worse lol

**Comment by prayag17** [comment]
The Fire tv and the android TV app don't use custom CSS and I am able to scroll the guide in Live TV

> also green to repos

What do you mean by this?

**Comment by Kin1976** [comment]
green meaning  new. 
anything i do does not work on firestick. the firestick stays the same
