### ISSUE TITLE
Feature Request: TV Skin

### ISSUE THREAD

**Issue by carl1330** [prayag17/JellyFlix#28]
Device-name: LG-TV WebOS
  type: TV
  
  This theme has some odd behaviour when using it in TV mode. If i have logos instead of titles enabled the play button is not accessible. 
  Also when selecting the titles like "Home" or "Favorites" it moves the entire screen.

**Comment by prayag17** [comment]
I will work on this as soon as I am free from my other work

**Comment by prayag17** [comment]
hey, I have started working on the tv fix for this skin, it should be done in a few weeks.

Track the progress here - https://github.com/prayag17/JellyFlix/projects/3

**Comment by MrVoid23** [comment]
Same behavior for me.Logos do not show at all.Will this get fixed?
