### ISSUE TITLE
button is blocked in windows client

### ISSUE THREAD

**Issue by fjjking** [prayag17/JellyFlix#29]
Quick Connect button Disappeared
![image](https://user-images.githubusercontent.com/25077204/152901569-397cb37f-ee62-4bee-87b5-e24eb00c5cee.png)
Client ver: https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.7.0-pre3
Jellyfin server ver: 10.7.7

**Comment by prayag17** [comment]
JMP V1.7.0 uses Jellyfin 10.8.0's client
