### ISSUE TITLE
Not working in JellyFin Roku App.

### ISSUE THREAD

**Issue by viriiguy** [prayag17/JellyFlix#3]
Device-name: Roku Ultra (JellyFin app)
  type: TV

The theme does not work properly on this device. Home doesn't change at all. Shows and movies do not show the actors. In general, very little of the theme seems to work in the Roku Jellyfin App.

**Comment by prayag17** [comment]
please share the images

**Comment by viriiguy** [comment]
I sent you an email with screenshots.

**Comment by prayag17** [comment]
I have not received them on my mail, please don't mail me the images, give them to me on GitHub comment

**Comment by viriiguy** [comment]
Ok, I will.
Randy Walker

**Comment by viriiguy** [comment]
Here you go.

![unnamed (4)](https://user-images.githubusercontent.com/5778225/100765178-3377df80-33c5-11eb-8e43-2b135ca78800.jpg)
![unnamed (3)](https://user-images.githubusercontent.com/5778225/100765184-3541a300-33c5-11eb-9ddb-abf315cd4380.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/5778225/100765194-370b6680-33c5-11eb-8fae-d811cdd1dfb3.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/5778225/100765199-383c9380-33c5-11eb-9e8c-e1b76d6a8204.jpg)

**Comment by prayag17** [comment]
Roku does not render HTML, I found out about it in this Reddit post -https://www.reddit.com/r/jellyfin/comments/k3wp0k/custom_css_and_the_roku_app/
