### ISSUE TITLE
Fully Offline?

### ISSUE THREAD

**Issue by sourpatched** [prayag17/JellyFlix#32]
I know copying and pasting the CSS code is the easiest way to make this work but for those that would like everything offline how would we go about this? Jellyfin works offline and I know I've had issues with this before being offline.

**Comment by prayag17** [comment]
Everything can't be offline as it needs to connect to netflix's assets server for fonts. You can try to copy the contents of the css to you custom css text area, A thing to note is that the server doesn't need to be connected to the internet for accessing the css, you only need a internet connection on the client

**Comment by sourpatched** [comment]
That makes sense. Could this be downloaded and placed inside Jellyfin web folder therefore it's saved locally and doesn't need to connect to Netflix server if the fonts are downloaded?

**Comment by prayag17** [comment]
You can but then for importing those fonts you need to know that location relative to the html and it can be finiky, so I don't recommend it.
