### ISSUE TITLE
unusual big movie icons

### ISSUE THREAD

**Issue by mairajha** [prayag17/JellyFlix#4]
have this issue since last few days - unusual big movie icons

![image](https://user-images.githubusercontent.com/52917522/104204485-27188500-544f-11eb-80bf-92ad6c9bbee1.png)

**Comment by prayag17** [comment]
Issue was fixed with commit [a30294af2e7fd081ddd276a4d96a9fb1de3c5538](https://github.com/prayag17/JellyFlix/commit/a30294af2e7fd081ddd276a4d96a9fb1de3c5538)
