### ISSUE TITLE
Favorite button color

### ISSUE THREAD

**Issue by vic-blt** [prayag17/JellyFlix#6]
https://github.com/prayag17/JellyFlix/blob/bf2c6ceebf21c58f3e6dc15ebeb48bae48311679/default.css#L219-L220
`color: #e50914;` should be removed because it makes the favorite button red even when the item is not a favorite.

**Comment by prayag17** [comment]
ok, I will remove it. Sorry for the late reply

**Comment by prayag17** [comment]
Sorry for the delay, I will add a fix for this in the next update
