### ISSUE TITLE
Ability to change buttons to white

### ISSUE THREAD

**Issue by Supergamer1337** [prayag17/JellyFlix#7]
As the title says, I'd love to the ability to easily change the buttons to a white color, but with the same red hover effect. Because as it currently stands, it doesn't seem to be the case.

This is particularly about the media playback buttons in the web player.

**Comment by prayag17** [comment]
Can you attach a image?

**Comment by Supergamer1337** [comment]
So, here's the image for the media playback as it currently looks:
![image](https://user-images.githubusercontent.com/46903500/112746472-45524380-8faf-11eb-80e4-87ff6b24071b.png)

Also, as you get the window width below 1600px, these buttons turn from this:
![image](https://user-images.githubusercontent.com/46903500/112746545-b85bba00-8faf-11eb-8a32-5df80b60c607.png)
To this:
![image](https://user-images.githubusercontent.com/46903500/112746557-c3164f00-8faf-11eb-963a-50ef5539b615.png)
And I don't know if that is intentional or not.

**Comment by prayag17** [comment]
Ooh that, I will change it with the next update. You will see a reddit post for it.

**Comment by prayag17** [comment]
This issue is fixed
