### ISSUE TITLE
Issues on iOS using Jellyfin app

### ISSUE THREAD

**Issue by tamburra** [prayag17/JellyFlix#8]
Theme does not look right on iOS through browser or through app. I have purged all cache in client side and on cloudflare with same results. Attaching some screenshots. 

![image](https://user-images.githubusercontent.com/16267805/115328345-795bf700-a15e-11eb-9a25-b9d839a8dd58.png)
![image](https://user-images.githubusercontent.com/16267805/115328336-75c87000-a15e-11eb-8bfc-be4c808b3f54.png)

Are the library thumbs suppose to no be a carrousel anymore?  I have many libraries so having to scroll past all these library thumbs is a bit much. 

![image](https://user-images.githubusercontent.com/16267805/115328401-92fd3e80-a15e-11eb-910c-d63496057684.png)

**Comment by prayag17** [comment]
Cn you tell me your device name?

**Comment by tamburra** [comment]
How can I gather this info?  I am running iOS v14.4.2 on Jellyfin 10.7.2.

**Comment by prayag17** [comment]
I meant your phone name like iPhone 12 or something cause I will need to find the dimension for that device

**Comment by tamburra** [comment]
aahh.  iPhone 12 Pro Max.

**Comment by prayag17** [comment]
Ok thank you. I will fix it today

**Comment by prayag17** [comment]
Can you check whether it is fixed or not?

**Comment by tamburra** [comment]
Currently I am not seeing any difference on my device on any of the pages.  I have cleared cache as well.  My screenshots above are still what I am currently seeing.

**Comment by prayag17** [comment]
Can you check if it is fixed?

**Comment by tamburra** [comment]
The main series page looks much better. The season view page still look the same. 

![image](https://user-images.githubusercontent.com/16267805/116626686-b02dcc00-a919-11eb-9e8e-7b711fb73e23.png)
![image](https://user-images.githubusercontent.com/16267805/116626710-b9b73400-a919-11eb-8115-25a2d9a53657.png)
![image](https://user-images.githubusercontent.com/16267805/116627273-cc7e3880-a91a-11eb-8a68-9ea94e795982.png)
![image](https://user-images.githubusercontent.com/16267805/116626733-c0de4200-a919-11eb-8e36-adc71042069c.png)

**Comment by prayag17** [comment]
The blank gap is fixed though I don't see any issue with the episode in me emulator

**Comment by tamburra** [comment]
I can confirm the blank gap is fixed on the season view page. 

The other issue on the season view page is that the episode images are overlaying on top of the episode description. 

I have attached more screenshots. 

I appreciate you making these fixes. I am happy to keep reporting. 

![image](https://user-images.githubusercontent.com/16267805/116783747-7a463000-aa5e-11eb-9e05-7946d7ace64a.png)
![image](https://user-images.githubusercontent.com/16267805/116783749-7d412080-aa5e-11eb-9b2a-c747576774ab.png)

**Comment by prayag17** [comment]
I can't fix the issue that I don't seen on my device emulator, but let me try to see it another device emulator but if that doesn't show me this issues I really cant fix it and then maybe it jf iOS app causing the issue

**Comment by prayag17** [comment]
Sorry man, I can't find this issue on any other device emulator also :(. Try uninstalling jf-mobile app and reinstalling it.

**Comment by tamburra** [comment]
I'll download the stylesheet and mess around to try and find a fix. I can confirm that the issue is the same in the safari browser as well.

I currently am running Jellyfin with docker using linuxserver container. I have re pulled and create new images with no change. 

Thank you for trying. I'll report back with any updates on my end when I can confirm.

**Comment by prayag17** [comment]
can you try the official jellyfin docker image?

**Comment by prayag17** [comment]
I am closing this issue as I cant seem to replicate it and no other person is getting this issue
